spring:
  profiles:
    active: local

###local 환경설정
---
spring:
  profiles: local
  h2:
    console:
      enabled: true



  #datasource:
  #  data: classpath:data-h2.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop




